platform :ios, '9.0'

target 'CSSModel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'CSSPrettyPrinted', '~> 0.1.0'

  target 'CSSModelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
